name: Run Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: videosdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Criar .env
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=testuser" >> .env
          echo "DB_PASSWORD=testpass" >> .env
          echo "DB_NAME=videosdb" >> .env

      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 10`; do
            if mysqladmin ping -h localhost -u root -proot --silent; then
              echo "MySQL is ready!"
              break
            else
              echo "Waiting for MySQL..."
              sleep 5
            fi
          done

      - name: Debug MySQL connection
        run: |
          echo "Testing MySQL connection..."
          mysql -h localhost -u root -proot -e "SHOW DATABASES;"

      - name: Grant privileges to testuser
        run: |
          mysql -h localhost -u root -proot -e "GRANT ALL PRIVILEGES ON videosdb.* TO 'testuser'@'%'; FLUSH PRIVILEGES;"

      - name: Rodar testes com Jest
        run: npm test
