name: Run Jest Tests

on:
  push:
    branches:
      - main # Roda o workflow quando houver push na branch main
  pull_request:
    branches:
      - main # Também roda quando um pull request for aberto na branch main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Jest
        run: npm test
